### PR TITLE
Test

### PR DESCRIPTION
**Pull request by sharanry**
Changed from "Design" to "Operations".

### CODE REVIEW

**Comment by SebastinSanty** [comment]
Great! Thanks for the PR :). Can you also solve the other issues as was mentioned in the group?

**Comment by sharanry** [comment]
Hey!, I am doing the changes as when I get the information. Solved a couple more issues just now. They are minor. Should I make a pull request for every minor change or do it periodically?

**Comment by SebastinSanty** [comment]
For a batch of information, it would be better having a new PR, as that would help in regular updation of the website.

**Comment by sharanry** [comment]
Okay! Thanks.

**Pull request merged**
